run_batch:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: ma_curated_radio
    mode:
      required: false
      default: replace
      selector:
        select:
          options:
            - replace
            - refill
unmute_artist:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: ma_curated_radio
    artist:
      required: true
      example: Maisie Peters
      selector:
        text:
forget_feedback:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: ma_curated_radio
